[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables for Netlify
[context.production.environment]
  VITE_API_URL = "https://adaptable-imagination.railway.app"

[context.deploy-preview.environment]
  VITE_API_URL = "https://adaptable-imagination.railway.app"

[context.branch-deploy.environment]
  VITE_API_URL = "https://adaptable-imagination.railway.app"